// js/questions.js
// 60問（各軸12問）: axis は UO/MC/HL/DS/RX、side はその軸の左文字
export const QUESTIONS = [
  // 1-12 U/O
  { id: 1, axis: "UO", side: "U", text: "考えを外に出すと整理できる" },
  { id: 2, axis: "UO", side: "U", text: "誰かに話すと落ち着く" },
  { id: 3, axis: "UO", side: "U", text: "モヤモヤは口にすると消える" },
  { id: 4, axis: "UO", side: "U", text: "相談しながら答えを作る" },
  { id: 5, axis: "UO", side: "U", text: "思ったことをまず言語化する" },
  { id: 6, axis: "UO", side: "O", text: "一人で考えるほど整理できる" },
  { id: 7, axis: "UO", side: "O", text: "話す前に頭の中で結論が固まる" },
  { id: 8, axis: "UO", side: "O", text: "感情は内側で処理したい" },
  { id: 9, axis: "UO", side: "O", text: "本音はすぐ言わない" },
  { id:10, axis: "UO", side: "O", text: "考えがまとまるまで黙る" },
  { id:11, axis: "UO", side: "U", text: "会話が思考のエンジンになる" },
  { id:12, axis: "UO", side: "O", text: "外に出すと逆に混乱する" },

  // 13-24 M/C
  { id:13, axis: "MC", side: "M", text: "場に合わせて自分を変えられる" },
  { id:14, axis: "MC", side: "M", text: "状況が変われば判断も変わる" },
  { id:15, axis: "MC", side: "M", text: "柔軟に立ち回るのが得意" },
  { id:16, axis: "MC", side: "M", text: "環境が違えば性格も切り替わる" },
  { id:17, axis: "MC", side: "M", text: "相手に合わせるのは苦じゃない" },
  { id:18, axis: "MC", side: "C", text: "一度決めた軸は簡単に変えない" },
  { id:19, axis: "MC", side: "C", text: "自分のルールがある" },
  { id:20, axis: "MC", side: "C", text: "合わせすぎると疲れる" },
  { id:21, axis: "MC", side: "C", text: "自分は自分、で動きたい" },
  { id:22, axis: "MC", side: "C", text: "一貫性がある方が安心する" },
  { id:23, axis: "MC", side: "M", text: "最適解はその場で変わる" },
  { id:24, axis: "MC", side: "C", text: "環境より信念を優先する" },

  // 25-36 H/L
  { id:25, axis: "HL", side: "H", text: "人間関係の温度を守りたい" },
  { id:26, axis: "HL", side: "H", text: "衝突はできるだけ避けたい" },
  { id:27, axis: "HL", side: "H", text: "相手の気持ちを優先しがち" },
  { id:28, axis: "HL", side: "H", text: "丸く収める方が価値がある" },
  { id:29, axis: "HL", side: "H", text: "空気を読むのは得意な方" },
  { id:30, axis: "HL", side: "L", text: "正しさが優先でいいと思う" },
  { id:31, axis: "HL", side: "L", text: "必要なら嫌われても言う" },
  { id:32, axis: "HL", side: "L", text: "感情より整合性を優先する" },
  { id:33, axis: "HL", side: "L", text: "結論重視で話したい" },
  { id:34, axis: "HL", side: "L", text: "遠回しよりストレートが楽" },
  { id:35, axis: "HL", side: "H", text: "関係維持のために言い方を選ぶ" },
  { id:36, axis: "HL", side: "L", text: "関係より結果が大事な時が多い" },

  // 37-48 D/S
  { id:37, axis: "DS", side: "D", text: "疲れてもやる時はやり切る" },
  { id:38, axis: "DS", side: "D", text: "締切があると燃える" },
  { id:39, axis: "DS", side: "D", text: "多少無理してでも前に進む" },
  { id:40, axis: "DS", side: "D", text: "勝ち筋を作るのが好き" },
  { id:41, axis: "DS", side: "D", text: "タフに動ける方だ" },
  { id:42, axis: "DS", side: "S", text: "省エネで長く続けたい" },
  { id:43, axis: "DS", side: "S", text: "無理すると一気に崩れる" },
  { id:44, axis: "DS", side: "S", text: "体力や気力の管理が最優先" },
  { id:45, axis: "DS", side: "S", text: "休みを設計してから動きたい" },
  { id:46, axis: "DS", side: "S", text: "一定ペースが得意" },
  { id:47, axis: "DS", side: "D", text: "短期集中で片付けがち" },
  { id:48, axis: "DS", side: "S", text: "消耗を避ける判断が多い" },

  // 49-60 R/X
  { id:49, axis: "RX", side: "R", text: "素の自分で出ることが多い" },
  { id:50, axis: "RX", side: "R", text: "感情や反応が顔に出やすい" },
  { id:51, axis: "RX", side: "R", text: "言ってしまうタイプだ" },
  { id:52, axis: "RX", side: "R", text: "演じるより本音が楽" },
  { id:53, axis: "RX", side: "R", text: "その場のノリで出ちゃう" },
  { id:54, axis: "RX", side: "X", text: "人に見せ方を選べる" },
  { id:55, axis: "RX", side: "X", text: "本音を隠して動ける" },
  { id:56, axis: "RX", side: "X", text: "立場でキャラを使い分ける" },
  { id:57, axis: "RX", side: "X", text: "表情や言い方を調整する" },
  { id:58, axis: "RX", side: "X", text: "演技っぽくなる自覚がある" },
  { id:59, axis: "RX", side: "R", text: "嘘が苦手で出る" },
  { id:60, axis: "RX", side: "X", text: "必要なら演じるのは普通" },
];
