// js/questions.js
export const QUESTIONS = [
  // 1-12 U/O
  { id: 1,  axis: "UO", side: "U", text: "嫌なことがあると、まず頭の中で整理する" },
  { id: 2,  axis: "UO", side: "O", text: "モヤモヤは人に話すと軽くなる" },
  { id: 3,  axis: "UO", side: "U", text: "感情を言葉にするのは少し時間がいる" },
  { id: 4,  axis: "UO", side: "O", text: "思ったことは割とすぐ口に出る" },
  { id: 5,  axis: "UO", side: "U", text: "一人で考える時間がないと落ち着かない" },
  { id: 6,  axis: "UO", side: "O", text: "感情は共有した方がスッキリする" },
  { id: 7,  axis: "UO", side: "U", text: "本音を話す前に何度もシミュレーションする" },
  { id: 8,  axis: "UO", side: "O", text: "その場の勢いで感情が出ることがある" },
  { id: 9,  axis: "UO", side: "U", text: "反論は後から思いつくことが多い" },
  { id: 10, axis: "UO", side: "O", text: "言いながら自分の気持ちが整理される" },
  { id: 11, axis: "UO", side: "U", text: "内側で納得しないと動けない" },
  { id: 12, axis: "UO", side: "O", text: "話しているうちに気持ちが固まる" },

  // 13-24 M/C
  { id: 13, axis: "MC", side: "M", text: "環境が変わると自然にキャラが変わる" },
  { id: 14, axis: "MC", side: "C", text: "合わない空気でも自分を崩さない" },
  { id: 15, axis: "MC", side: "M", text: "相手によって話し方がかなり変わる" },
  { id: 16, axis: "MC", side: "C", text: "無理に合わせるくらいなら距離を取る" },
  { id: 17, axis: "MC", side: "M", text: "周囲に合わせるのは苦ではない" },
  { id: 18, axis: "MC", side: "C", text: "「自分はこう」が強い" },
  { id: 19, axis: "MC", side: "M", text: "空気が違えば自分も変わる" },
  { id: 20, axis: "MC", side: "C", text: "自分の基準はあまり変わらない" },
  { id: 21, axis: "MC", side: "M", text: "とりあえず合わせて様子を見る" },
  { id: 22, axis: "MC", side: "C", text: "合わないと感じたら早めに離れる" },
  { id: 23, axis: "MC", side: "M", text: "役割が変われば自分も変わる" },
  { id: 24, axis: "MC", side: "C", text: "自分らしさは守りたい" },

  // 25-36 H/L
  { id: 25, axis: "HL", side: "H", text: "会話では相手の気持ちを優先する" },
  { id: 26, axis: "HL", side: "L", text: "会話では主導権を意識する" },
  { id: 27, axis: "HL", side: "H", text: "争いは避けたい" },
  { id: 28, axis: "HL", side: "L", text: "必要なら強く出る" },
  { id: 29, axis: "HL", side: "H", text: "場の空気が悪いと落ち着かない" },
  { id: 30, axis: "HL", side: "L", text: "流れが悪いと修正したくなる" },
  { id: 31, axis: "HL", side: "H", text: "誰かが傷ついていると気になる" },
  { id: 32, axis: "HL", side: "L", text: "会話の方向性は自分で決めたい" },
  { id: 33, axis: "HL", side: "H", text: "みんなが安心しているか気になる" },
  { id: 34, axis: "HL", side: "L", text: "みんなが従っているか気になる" },
  { id: 35, axis: "HL", side: "H", text: "調和を保つ方が大事" },
  { id: 36, axis: "HL", side: "L", text: "結果を出す方が大事" },

  // 37-48 D/S
  { id: 37, axis: "DS", side: "D", text: "人と長くいるとかなり疲れる" },
  { id: 38, axis: "DS", side: "S", text: "人と長くいても平気な方だ" },
  { id: 39, axis: "DS", side: "D", text: "気を使った日はぐったりする" },
  { id: 40, axis: "DS", side: "S", text: "気を使ってもそこまで疲れない" },
  { id: 41, axis: "DS", side: "D", text: "初対面の後は反省会をする" },
  { id: 42, axis: "DS", side: "S", text: "初対面の後はすぐ切り替える" },
  { id: 43, axis: "DS", side: "D", text: "トラブルを引きずる" },
  { id: 44, axis: "DS", side: "S", text: "トラブルは割とすぐ忘れる" },
  { id: 45, axis: "DS", side: "D", text: "人間関係は体力を使う" },
  { id: 46, axis: "DS", side: "S", text: "人間関係はそこまで負担じゃない" },
  { id: 47, axis: "DS", side: "D", text: "無理すると急にシャットダウンする" },
  { id: 48, axis: "DS", side: "S", text: "無理しても割と持つ" },

  // 49-60 R/X
  { id: 49, axis: "RX", side: "R", text: "基本的に素のままでいる" },
  { id: 50, axis: "RX", side: "X", text: "場面ごとにキャラを使い分ける" },
  { id: 51, axis: "RX", side: "R", text: "本音が態度に出やすい" },
  { id: 52, axis: "RX", side: "X", text: "本音は隠せる" },
  { id: 53, axis: "RX", side: "R", text: "嫌な相手に愛想は使えない" },
  { id: 54, axis: "RX", side: "X", text: "嫌な相手にも普通に接せる" },
  { id: 55, axis: "RX", side: "R", text: "嘘をつくのは苦手" },
  { id: 56, axis: "RX", side: "X", text: "必要なら嘘も使う" },
  { id: 57, axis: "RX", side: "R", text: "自分を大きく見せるのは苦手" },
  { id: 58, axis: "RX", side: "X", text: "場のためなら盛れる" },
  { id: 59, axis: "RX", side: "R", text: "好き嫌いが態度に出やすい" },
  { id: 60, axis: "RX", side: "X", text: "状況次第で人格は変えられる" },
];
